### ISSUE TITLE
The Current App menus open wrong folders

### ISSUE THREAD

**Issue by revolter** [scinfu/NCSimulatorPlugin#4] opened 2015-05-27 07:52 UTC
Upon clicking `Go To Documents` or `Go To Application` from the `Current App` section, it opens up the folders corresponding to another app.

Also, is it normal to get stuck on `Refreshing...`?

**Comment by scinfu** [comment] 2015-06-16 10:17
Yes , is normal "Refreshing" state.
Is symptomatic the bug that opens a wrong folder?
I can't reproduce this bug.

**Comment by revolter** [comment] 2015-06-16 11:29
It works now. I thought it was because I had multiple apps "installed" in the simulator. I'll close this for now and open it if I have more detailed information.

**Comment by revolter** [comment] 2015-06-24 13:53
It started again. It simply opens up the wrong app's folder to another app that is installed on the simulator.

**Comment by scinfu** [comment] 2015-07-01 07:15
Fixed in pull request https://github.com/scinfu/NCSimulatorPlugin/pull/7

**Closed by scinfu** 2015-07-01 07:15 UTC
